### PR TITLE
Add operator whitelisting

### PR DESCRIPTION
**Pull request by Hyodar**

### CODE REVIEW

**Review by taco-paco — COMMENTED** [review]
I mean code looks ok. But what is the purpose of this and how is this not a centralization?

Operator before joining needs to be included in whitelist

**Comment by taco-paco** [comment]
This seems to be critical change for me I guess needs to be discussed with NEAR.

**Comment by Hyodar** [comment]
This is the expected behavior for testnet for now. We'll have only a small number of operators we're closely working with. Has already been discussed with NEAR

**Review by taco-paco — APPROVED** [review]
LGTM. I would add a small TODO or note marking that its supposed to be removed

**Pull request merged**
